### ISSUE TITLE
Standalone preset?

### ISSUE THREAD

**Issue by ME1312** [BtoBastian/bStats-Metrics#21]
One of my add-ons are standalone (they don't run on any API listed). This wouldn't be a problem, since I can just port over the metrics class, but all the presets on the site look to require information that doesn't exist.

**Comment by BtoBastian** [comment]
About what kind of "add-on" are we talking about?

**Comment by ME1312** [comment]
[SubServers.Host](https://www.spigotmc.org/resources/subservers-host.38833/)

**Comment by ME1312** [comment]
Anything word on this?

**Comment by DoNotSpamPls** [comment]
@ME1312 There is a category called "Other" implemented in bStats. Maybe the plugins could be added manually to that and only with some of the charts. I can try to make a Standalone category this week, although I would need feedback on what charts would you want exactly. Also we'd need a metrics class which doesn't rely on bukkit/bungee/sponge, I hope you can help me with that.

**Comment by BtoBastian** [comment]
I added the "Other" category about 1 or 2 month ago. Just tell me your bStats name and your plugin name.

**Comment by ME1312** [comment]
**ME1312** with **SubServers Host** (please keep the space if you can)

**Comment by BtoBastian** [comment]
Hey,

I just added the "plugin" to your account. (https://bstats.org/plugin/other/SubServers%20Host)
Some notes about the "other"-category:
* A Metrics-class can be found here. Depending on your needs, you can adjust some of the stuff like the logger: https://gist.github.com/BtoBastian/6d59583dbc891f1c0426919443b75f4e
* The "other" category has no default charts -> Every chart must be implemented as a custom chart. This includes the Servers and Players charts. You should give them the chart id `servers` and `players`, otherwise the boxes with "Servers (Current/Record): x/z" won't work.
* This category does **not** appear in the plugin-list, as it's less restricted than normal plugins.

Feel free to ask, if you have any questions.

**Comment by ME1312** [comment]
Could you add the location charts to the other category, since they don't appear to rely on the data being sent?
